default:
	gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.5 -o Instantiation-1.5.pdf Instantiation.pdf
	gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.5 -o FMLMetaModel-1.5.pdf FMLMetaModel.pdf
	gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.5 -o BPMNSubsetExample-1.5.pdf BPMNSubsetExample.pdf
	gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.5 -o MultilevelArchitecture-1.5.pdf MultilevelArchitecture.pdf
	gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.5 -o Metamodel-1.5.pdf Metamodel.pdf
	gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.5 -o AcmeFullArchitecture-1.5.pdf AcmeFullArchitecture.pdf
	gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.5 -o ToolingArchitecture-1.5.pdf ToolingArchitecture.pdf
